config/routes.rb
Rails.application.routes.draw do

  # root "welcome#home"
  get '/signin' , to: "sessions#new"
  post '/signin', to: "sessions#create"
  delete '/sessions', to: "sessions#destroy"
  root 'welcome#home'

  # get '/auth/facebook/callback' => 'sessions#create'
  get '/auth/:provider/callback' => 'sessions#create'

  resources :votes
  resources :users do 
  get '/showvotes' , to: "sessions#vote_index" end
  resources :topics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ActiveRecord::Base
    # Adds methods to set and authenticate against a BCrypt password. 
    #   This mechanism requires you to have a XXX_digest attribute. Where XXX is the attribute name of your desired password.
     has_secure_password

    #  Validations are used to ensure that only valid data is saved into your database. 
  #  Model-level validations are the best way to 
  # ensure that only valid data is saved into your database. They are database agnostic, cannot 
  #   be bypassed by end users, and are convenient to test and maintain.
     validates :name, presence: true
     validates :password, presence: true
     validates :name, uniqueness: {
        scope: [:name],
        # session["error_message"] = "Cannot release the same name twice."
      }
    # has_many association indicates a one-to-many connection with another model. 
    has_many :votes

    # A has_many :through association is often used to set up a many-to-many connection with another model.
    #   This association indicates that the declaring model can be matched with zero or more instances of another model 
    #   by proceeding through a third model
    has_many :topics, through: :votes

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # Check that the user has the right authorization to access clients.
      #  skip_before_action :authentication_required, only: [:new, :create, :facebook, :show]
      # skip_before_action :authentication_required
      skip_before_action [:new, :create, :facebook, :show], raise: false
      
    def new 
        @user = User.new
    end 

def self.facebook(auth)
  
  # auth.require(:info).permit(:name, :email)
  @user = User.find_by(:name => auth['info']['name'])
  if !(@user = User.find_by(:name => auth['info']['name']))
  @user = User.create(password: auth['uid']) do |u|
    u.name = auth['info']['name']
    u.email = auth['info']['email']
    # u.image = auth['info']['image']
end
end
auth.clear


return @user
 
end
    def create
    #  binding.pry
     user = User.new(user_params)
    if user.valid?
      user.save
      session[:user] = user
      redirect_to user_path(user)
    else
      # To check which validations failed on an invalid attribute, you can use errors.details[:attribute].
      #  It returns an array of hashes with an :error key to get the symbol of the validator:
      user.errors.details[:name] 
      redirect_to signin_path
      
    end
  

    end


    def show 
      # binding.pry
    # @user = User.find_by(id: params[:id])
    @user = session[:user] 
    end 
    
  # The keyword private tells Ruby that all methods defined from now on, are supposed to be private. 
  #   They can be called from within the object (from other methods that the class defines), but not from outside.
    private 
    


  def user_params
      params.require(:user).permit(:name, :password)
  end 


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% session[:current_user]=@user%>
<%session[:current_user]=session[:user] %>

  <p><strong><%= @user["name"]%>'s Topics</p>


  <ul>
 <% @user_topics = []%>
       
  <%Topic.all.each do |n| %>

  <%if n.user_id == session["user"]["id"]%>
  <% @user_topics << n%>
  <% end%>

  <%end%>
  <%@user_topics %>

  <%@user_topics.each do |attr| %>

    
          <li> <%= link_to " #{attr.name}", topic_path(attr)%> </li>

     

  <% end %>

app/views/users/new.html.erb
<%= form_for @user do |f|%>
    <%= f.label :name %>
    <%= f.text_field :name %>


    <%= f.label :password %>
    <%= f.password_field :password %>
    

    <%= f.submit "Create User"%>
    <h1><%= link_to('Log in with Github!', '/auth/github') %>
<% end %>

app/views/users/show.html.erb
<% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
  <% end %>

  <%= render "form" %> 

</ul>




   


<%= link_to "See Topics", topics_path %> 
<p><%= link_to "New Topic", new_topic_path %></p>