config/routes.rb
Rails.application.routes.draw do

  # root "welcome#home"
  get '/signin' , to: "sessions#new"
  post '/signin', to: "sessions#create"
  delete '/sessions', to: "sessions#destroy"
  root 'welcome#home'

  # get '/auth/facebook/callback' => 'sessions#create'
  get '/auth/:provider/callback' => 'sessions#create'

  resources :votes
  resources :users do 
  get '/showvotes' , to: "sessions#vote_index" end
  resources :topics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
  <!DOCTYPE html>
  <html>
    <head>
      <title>Vote</title>
      <%= csrf_meta_tags %>
  
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
    <body>
    
   

      <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          <a class="navbar-brand" href="<%= root_url %>"/>Home</a>
      
     
         
          <% if !session[:user] %>
            <%= link_to "Sign Up", new_user_path, class: "navbar-brand" %>
            <%= link_to "Log in", signin_path, class: "navbar-brand" %>
          <%else%>
       
            <%= link_to "#{session[:user]["name"]}'s profile", user_path(session[:user]["id"]), class:"navbar-brand"%>
            <%= link_to "Log Out", sessions_path, class:"navbar-brand",method:'delete' %>
           <% end %>
  
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
  
      <!-- content -->
      <div class="container"  role="main">
        <%= yield %>
      </div>
    </body>
  </html>